---
title: "Figure 1"
author: "R.J. Beck"
date: "17/08/2020"
output: html_document
---




```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_knit$set(root.dir="path/to/LAG_TIM_BIOMARKERS/")
require(ggplot2)


```

Following is results of my image analysis:
```{R}
setwd("IMAGE_ANALYSIS/Exp16_merged_training/cropped_ims_results")

x <- read.csv("manual_counts.csv")

y <- x[,c("image","green","green_ilastik")]
y$color<-"green"
z <-  x[,c("image","red","red_ilastik")] 
z$color <- "red"

colnames(y)[2:3] <- c("manual","ilastik")
colnames(z)[2:3] <- c("manual","ilastik")

x <- rbind(y,z)

require(ggplot2)

p1b <- ggplot(x,aes(x=manual,y=ilastik,color=color,shape=color))+
  geom_point(size=2)+
  geom_abline(slope=1,intercept=0)+
    theme_classic(base_size = 10)+
  scale_x_continuous("manual counted nuclei")+
  scale_y_continuous("ilastik predicted nuclei")+
  scale_color_discrete("",labels=c(expression(S-G[2]-M),expression(G[1])))+
  scale_shape_discrete("",labels=c(expression(S-G[2]-M),expression(G[1])))
p1b
```

```{r}

require(ggplot2)
setwd("IMAGE_ANALYSIS/Exp16_results")
red <- read.csv("redNuclei_allIlastikDensityCounts.csv",header = F)
green <- read.csv("greenNuclei_allIlastikDensityCounts.csv",header = F)

red <- red[order(red$V1),]
green <- green[order(green$V1),]

df <- red
names(df) <- c("id","red")
df$green <- green$V2
df$ratio <- df$green/df$red

id <- df$id[1]

splitr <- function(id){
  x1 <- strsplit(id,split="No.")[[1]][2]
  x2 <- strsplit(x1,split=" ")[[1]][1]
  x3 <- strsplit(x2,split="-")[[1]]
  data.frame(mouse=x3[1],field=x3[2])
}

id_df <- do.call(rbind,lapply(df$id,splitr))


mice <- c("No.1-","No.2-","No.4-","No.5-","No.6-","No.7-","No.8-","No.9-","No.10-","No.11-","No.12-","No.13-")
days <- c(1,1,3,3,5,5,7,7,10,10,14,14) 

df$day <- NaN

for(i in 1:length(mice)){
  
  df$day[grepl(mice[i],df$id)] <- days[i]
}

df <- cbind(df,id_df)
#df$total <- df$red+df$green

x <- reshape2::melt(df,id.vars=c("day","id"))
x$value <- as.numeric(x$value)
y <- aggregate(x["value"],by=x[c("day","variable")],mean)
z <- aggregate(x["value"],by=x[c("day","variable")],sd)

y$sd <- z$value


GR_dat <- y[y$variable=="ratio",c("day","value","sd")]
## min max scaling for the GR data
GR_dat$scale <- (GR_dat$value-min(GR_dat$value))/(max(GR_dat$value)-min(GR_dat$value))



p1c <- ggplot(subset(x,variable=="red"),aes(x=day,y=value))+
  geom_jitter(color="red",height=0,width=0.5)+
  geom_point(data=subset(y,variable=="red"),size=3)+
  geom_errorbar(data=subset(y,variable=="red"),aes(ymin=value-sd,ymax=value+sd))+ 
  theme_classic(base_size = 10)+
  scale_y_continuous(expression(G[1]~nuclei~per~field))+
  scale_x_continuous("day after CTL transfer",breaks=c(1,3,5,7,10,14))
p1c

p1d <- ggplot(subset(x,variable=="green"),aes(x=day,y=value))+
  geom_jitter(color="red",height=0,width=0.5)+
  geom_point(data=subset(y,variable=="green"),size=3)+
  geom_errorbar(data=subset(y,variable=="green"),aes(ymin=value-sd,ymax=value+sd))+ 
  theme_classic(base_size = 10)+
  scale_y_continuous(expression(S-G[2]-M~nuclei~per~field))+
  scale_x_continuous("day after CTL transfer",breaks=c(1,3,5,7,10,14))
p1d

p1e <- ggplot(subset(x,variable=="ratio"),aes(x=day,y=value))+
  geom_jitter(color="red",height=0,width=0.5)+
  geom_point(data=subset(y,variable=="ratio"),size=3)+
  geom_errorbar(data=subset(y,variable=="ratio"),aes(ymin=value-sd,ymax=value+sd))+  
  theme_classic(base_size = 10)+
  scale_y_continuous(expression(S-G[2]-M~":"~G[1]~ratio),breaks=seq(0,4.5,0.5))+
  scale_x_continuous("day after CTL transfer",breaks=c(1,3,5,7,10,14))
p1e


df <-df[order(as.numeric(df$mouse),df$field),]
```

```{r}
ctl <- read.csv("IMAGE_ANALYSIS/ctl.csv")

ctl_mean <- aggregate(ctl["ctl"],by=ctl["day"],mean)
names(ctl_mean)[2]<-"value"
ctl_sd <- aggregate(ctl["ctl"],by=ctl["day"],sd)

ctl_mean$sd <- ctl_sd$ctl

p1f <- ggplot(ctl_mean,aes(x=day,y=value))+
  geom_jitter(data=ctl,aes(y=ctl),height=0,width = 0.5,color="red")+
  geom_point(size=3)+
  geom_errorbar(aes(ymin=value-sd,ymax=value+sd))+
  theme_classic(base_size = 10)+
  scale_y_continuous(expression(CTLs~per~field),breaks=seq(0,150,25),sec.axis = sec_axis(trans=~.*(10^5/650),name = expression(estimated~CTL~density~mm^-3)))+
  scale_x_continuous("day after CTL transfer",breaks=c(1,3,5,7,10,14))
p1f

ctl_dat <- ctl_mean
ctl_dat$scale <- (ctl_dat$value-min(ctl_dat$value))/(max(ctl_dat$value)-min(ctl_dat$value))
ctl_dat <- ctl_dat[ctl_dat$day<14,]

ctl_dat$value <- ctl_dat$value*(10^5/650)
ctl_dat$sd <- ctl_dat$sd*(10^5/650)

ctl <- rbind(ctl,data.frame(X=NA,color=NA,mouse=2,field=3,day=1,ctl=NA))## one missing piece of data

ctl <-ctl[order(ctl$mouse,ctl$field),]

corr_df <- cbind(df[,c("ratio","day","mouse","field")],ctl=ctl$ctl)

p1g <- ggplot(corr_df,aes(x=ctl,y=ratio))+
  geom_point()+
  theme_classic(base_size = 10)+
  scale_y_continuous(expression(S-G[2]-M~":"~G[1]~ratio),breaks=seq(0,4.5,0.5))+
  scale_x_continuous(expression(CTLs~per~field),breaks=seq(0,150,25))
p1g

cor(corr_df$ratio[!is.na(corr_df$ctl)],corr_df$ctl[!is.na(corr_df$ctl)])

```

Save various processed data for later use:

```{r}
saveRDS(ctl_dat,"PAR_EST/ctl_dat.Rds")
saveRDS(GR_dat,"PAR_EST/GR_dat.Rds")
```



